name-template: "$RESOLVED_VERSION 🚀"
tag-template: "$RESOLVED_VERSION"

categories:
    - title: "🚀 Features"
      labels:
          - "Type - Feature"
    - title: "🐛 Bug Fixes"
      labels:
          - "Type - Bug"
    - title: "🧰 Maintenance"
      label: "chore"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

exclude-labels:
    - "Skip Release"

version-resolver:
    major:
        labels:
            - "Release - Major"
    minor:
        labels:
            - "Release - Minor"
    patch:
        labels:
            - "Release - Patch"
    default: "Release - Patch"

template: |
    ## What's Changed

    $CHANGES

    ## Thanks to

    $CONTRIBUTORS

autolabeler:
    - label: "Type - Chore"
      branch:
          - '/chore\/.+/'

    - label: "Type - Bug"
      branch:
          - '/fix\/.+/'
          - '/bugfix\/.+/'

    - label: "Type - Feature"
      branch:
          - '/feature\/.+/'
          - '/feat\/.+/'

    - label: "Type - Refactoring"
      branch:
          - '/refacto\/.+/'
          - '/refactoring\/.+/'

    - label: "Type - Dependencies"
      branch:
          - '/deps\/.+/'
          - '/dep\/.+/'
          - '/dependencies\/.+/'
          - '/dependency\/.+/'
