monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                level: debug
                max_files: 2
                path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.log"
                formatter: monolog.formatter.extra_log
                channels: ["!event"]

when@test:
    monolog:
        handlers:
            main:
                type: rotating_file
                level: debug
                max_files: 2
                path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.log"
                formatter: monolog.formatter.extra_log
                channels: ["!event"]

when@prod:
    monolog:
        handlers:
            main:
                type: rotating_file
                level: notice
                max_files: 7
                path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.log"
                formatter: monolog.formatter.extra_log

            error:
                type: fingers_crossed
                action_level: error
                excluded_http_codes: [400, 404, 405]
                buffer_size: 50
                handler: deduplicated

            deduplicated:
                type: deduplication
                handler: symfony_mailer

            symfony_mailer:
                type: symfony_mailer
                from_email: "noreply@needlify.com"
                to_email: "log@needlify.com"
                subject: "An Error or something worse Occurred!"
                level: notice
                formatter: monolog.formatter.html
                content_type: text/html
