twig:
    default_path: "%kernel.project_dir%/templates"
    paths:
        "%kernel.project_dir%/public/images": images

    globals:
        uploadDir: "%app.thumbnails.upload_dir%"
        banner: '@App\Provider\BannerProvider'
        appEnv: "%env(APP_ENV)%"

when@test:
    twig:
        strict_variables: true
