twig:
    default_path: "%kernel.project_dir%/templates"
    paths:
        "%kernel.project_dir%/public/images": images

    globals:
        uploadDir: "%app.thumbnails.upload_dir%"

when@test:
    twig:
        strict_variables: true
