version: "3.8"

services:
    database:
        command: --max-allowed-packet=64MB
        container_name: needlify-database
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - data:/var/lib/mariadb
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: needlify-mail
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - 8081:80
        networks:
            - dev

    adminer:
        container_name: needlify-adminer
        image: adminer
        ports:
            - 8082:8080
        networks:
            - dev

    web:
        container_name: needlify-web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            # - ./apache:/etc/apache2/sites-enabled
        networks:
            - dev
        depends_on:
            - database

    matomo:
        networks:
            - dev
        image: matomo
        depends_on:
            - database
        ports:
            - 8083:80
        environment:
            MATOMO_DATABASE_HOST: database
            MATOMO_DATABASE_ADAPTER: mysql
            MATOMO_DATABASE_TABLES_PREFIX: matomo_
            MATOMO_DATABASE_USERNAME: root
            MATOMO_DATABASE_PASSWORD: password
            MATOMO_DATABASE_DBNAME: matomo
        volumes:
            - matomo:/var/www/html

volumes:
    data:
    matomo:

networks:
    dev:
