name: Security Checker

on:
    push:
        branches: [master, dev]
    pull_request:
        branches: [master, dev]

jobs:
    php:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true

        steps:
            - uses: actions/checkout@v2

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - uses: actions/checkout@v2
            - uses: actions/cache@v3
              id: cache-db
              with:
                  path: ~/.symfony/cache
                  key: db

            - uses: symfonycorp/security-checker-action@v3

            - name: Display the vulnerabilities as JSON
              run: echo ${{ steps.security-check.outputs.vulns }}

    node:
        strategy:
            fail-fast: true

        permissions:
            contents: read # for actions/checkout to fetch code
            security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: nodejsscan scan
              id: njsscan
              uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
              with:
                  args: ". --sarif --output results.sarif || true"

            - name: Upload njsscan report
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: results.sarif
