name: "Update Changelog"

on:
    release:
        types: [released]

jobs:
    update:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true

        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create release branch
              run: git checkout -b release/${{ github.event.release.tag_name }}

            - name: Initialize mandatory git config
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email noreply@github.com

            - name: Update Changelog
              uses: stefanzweifel/changelog-updater-action@v1
              with:
                  latest-version: ${{ github.event.release.tag_name }}
                  release-notes: ${{ github.event.release.body }}

            - name: Commit updated CHANGELOG
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: release/${{ github.event.release.tag_name }}
                  commit_message: Update CHANGELOG.md
                  file_pattern: CHANGELOG.md

            - name: Create pull request into master
              uses: thomaseizinger/create-pull-request@1.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  head: release/${{ github.event.release.tag_name }}
                  base: master
                  title: ${{ github.event.release.tag_name }} into master
                  reviewers: ${{ github.event.issue.user.login }}
                  body: |
                      Hi!
                      This PR was created in response workflow running.
                      I've updated the version name

            - name: Create pull request to dev
              uses: thomaseizinger/create-pull-request@1.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  head: release/${{ github.event.release.tag_name }}
                  base: dev
                  title: ${{ github.event.release.tag_name }} into dev
                  reviewers: ${{ github.event.issue.user.login }}
                  body: |
                      Hi!
                      This PR was created in response workflow running.
                      I've updated the version name
